plugins {
    id 'com.android.library'
}

android {
    namespace 'com.pydroid.libaci'
    compileSdk 34

    defaultConfig {
        minSdk 24
        targetSdk 34
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation project(':aidl-aci-core')
    implementation 'androidx.annotation:annotation:1.7.1'
}
